<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class StaffController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->query('search');

        // 1. Ambil User dengan role Admin atau Staff
        $query = User::whereIn('role', ['admin', 'staff']);

        // 2. Search Logic
        if ($search) {
            $query->where(function ($q) use ($search) {
                $q->where('full_name', 'ilike', "%{$search}%")
                    ->orWhere('email', 'ilike', "%{$search}%");
            });
        }

        // 3. Eager Load & Count Tasks
        $staffMembers = $query->withCount(['assignedTasks as active_tasks_count' => function ($query) {
            $query->whereIn('status', ['active', 'in_progress', 'review']);
        }, 'assignedTasks as completed_tasks_count' => function ($query) {
            $query->where('status', 'completed');
        }])
            ->orderBy('role', 'asc') // Admin dulu baru staff
            ->orderBy('full_name', 'asc')
            ->paginate(10)
            ->withQueryString();

        // 4. Logic Online Status
        $onlineUserIds = DB::table('sessions')
            ->whereNotNull('user_id')
            ->where('last_activity', '>=', now()->subMinutes(5)->timestamp)
            ->pluck('user_id')
            ->toArray();

        // 5. Statistik
        $totalStaff = User::where('role', 'staff')->count();
        $totalAdmins = User::where('role', 'admin')->count();

        return view('admin.staff.index', compact('staffMembers', 'onlineUserIds', 'totalStaff', 'totalAdmins'));
    }

    public function create()
    {
        return view('admin.staff.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'full_name' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|min:8',
            'role' => 'required|in:admin,staff',
        ]);

        User::create([
            'full_name' => $request->full_name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'role' => $request->role,
            // Default avatar generated by UI Avatars di View
        ]);

        return redirect()->route('admin.staff.index')->with('success', 'Team member baru berhasil ditambahkan.');
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('admin.staff.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $request->validate([
            'full_name' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email,' . $id,
            'role' => 'required|in:admin,staff',
        ]);

        $data = [
            'full_name' => $request->full_name,
            'email' => $request->email,
            'role' => $request->role,
        ];

        // Update password hanya jika diisi
        if ($request->filled('password')) {
            $request->validate(['password' => 'min:8']);
            $data['password'] = Hash::make($request->password);
        }

        $user->update($data);

        return redirect()->route('admin.staff.index')->with('success', 'Data staff berhasil diperbarui.');
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);

        // Prevent deleting self
        // Ganti auth()->id() menjadi Auth::id()
        if ($user->id == Auth::id()) { // <--- 2. UBAH DI SINI
            return back()->with('error', 'Anda tidak dapat menghapus akun sendiri.');
        }

        $user->delete();
        return back()->with('success', 'Staff berhasil dihapus.');
    }
}
